#pragma once
// StateMachine
#define MANIFEST_NODE_STATE_MACHINE							10

// State Machine Nodes
#define MANIFEST_STATE_MACHINE_NODE_ACTIVESTATE				137

// Nodes
#define MANIFEST_NODE_ANIMWITHEVENTS						104
#define MANIFEST_NODE_APPLYBINDPOSE							115
#define MANIFEST_NODE_APPLYGLOBALTIME						119
#define MANIFEST_NODE_BASICUNEVENTERRAIN					136
#define MANIFEST_NODE_BLEND2								107
#define MANIFEST_NODE_BLEND2X2								149
#define MANIFEST_NODE_BLENDALL								169
#define MANIFEST_NODE_BLENDN								108
#define MANIFEST_NODE_BLENDNXM								147
#define MANIFEST_NODE_CLOSESTANIM							130
#define MANIFEST_NODE_EMITREQUESTONDISCRETEEVENT			153
#define MANIFEST_NODE_EXTRACTJOINTINFO						152
#define MANIFEST_NODE_FEATHERBLEND2							114
#define MANIFEST_NODE_FILTERTRANSFORMS						105
#define MANIFEST_NODE_FREEZE								126
#define MANIFEST_NODE_GUNAIMIK								150
#define MANIFEST_NODE_HEADLOOK								122
#define MANIFEST_NODE_HIPSIK								129
#define MANIFEST_NODE_LASTFRAMESTRANSFORMS					126
#define MANIFEST_NODE_LOCKFOOT								121
#define MANIFEST_NODE_MIRRORTRANSFORMS						135
#define MANIFEST_NODE_PASSTHROUGH							134
#define MANIFEST_NODE_PLAYSPEEDMODIFIER						125
#define MANIFEST_NODE_PREDICTIVEUNEVENTERRAIN				138
#define MANIFEST_NODE_RETARGET								161
#define MANIFEST_NODE_SCALECHARACTER						162
#define MANIFEST_NODE_SCALETODURATION						151
#define MANIFEST_NODE_SEQUENCE								133
#define MANIFEST_NODE_SINGLEFRAME							109
#define MANIFEST_NODE_SMOOTHTRANSFORMS						500
#define MANIFEST_NODE_SUBTRACTIVEBLEND						170
#define MANIFEST_NODE_SWITCH								131
#define MANIFEST_NODE_TWOBONEIK								120
#define MANIFEST_NODE_OPERATORARITHMETIC					111
#define MANIFEST_NODE_OPERATORFLOATSTOVECTOR3				144
#define MANIFEST_NODE_OPERATORFUNCTION						110
#define MANIFEST_NODE_OPERATORNOISEGEN						113
#define MANIFEST_NODE_OPERATORONEINPUTARITHMETIC			112
#define MANIFEST_NODE_OPERATORRAMPFLOAT						143
#define MANIFEST_NODE_OPERATORRANDOMFLOAT					146
#define MANIFEST_NODE_OPERATORRATEOFCHANGE					173
#define MANIFEST_NODE_OPERATORRAYCAST						141
#define MANIFEST_NODE_OPERATORRERANGE						112
#define MANIFEST_NODE_OPERATORSMOOTHFLOAT					142
#define MANIFEST_NODE_OPERATORSMOOTHVECTOR3					142
#define MANIFEST_NODE_OPERATORVECTOR3ANGLE					174
#define MANIFEST_NODE_OPERATORVECTOR3ARITHMETIC				111
#define MANIFEST_NODE_OPERATORVECTOR3CROSSPRODUCT			172
#define MANIFEST_NODE_OPERATORVECTOR3DISTANCE				171
#define MANIFEST_NODE_OPERATORVECTOR3DOT					164
#define MANIFEST_NODE_OPERATORVECTOR3LENGTH					171
#define MANIFEST_NODE_OPERATORVECTOR3NORMALISE				175
#define MANIFEST_NODE_OPERATORVECTOR3ONEINPUTARITHMETIC		185
#define MANIFEST_NODE_OPERATORVECTOR3RATEOFCHANGE			173
#define MANIFEST_NODE_OPERATORVECTOR3TOFLOATS				154
#define MANIFEST_NODE_ACTIVEANIMATION						123
#define MANIFEST_NODE_HARDKEYFRAME							123
#define MANIFEST_NODE_LOCALSOFTKEYFRAME						123
#define MANIFEST_NODE_RAGDOLL								123
#define MANIFEST_NODE_SOFTKEYFRAME							123
#define MANIFEST_NODE_SOFTKEYFRAMEANDACTIVEANIMATION		123

// Conditions
#define MANIFEST_COND_CONTROLPARAMINRANGE					609
#define MANIFEST_COND_CONTROLPARAMTEST						616
#define MANIFEST_COND_ATEVENT								604
#define MANIFEST_COND_DURINGEVENT							605
#define MANIFEST_COND_FRACTIONTHROUGHDURATIONEVENT			610
#define MANIFEST_COND_FRACTIONTHROUGHSOURCE					603
#define MANIFEST_COND_INDURATIONEVENT						618
#define MANIFEST_COND_INEVENTRANGE							611
#define MANIFEST_COND_INSUBSTATE							617
#define MANIFEST_COND_USERDATAEVENT							602
#define MANIFEST_COND_GROUNDCONTACT							614
#define MANIFEST_COND_PHYSICSAVAILABLE						612
#define MANIFEST_COND_PHYSICSINUSE							613
#define MANIFEST_COND_PHYSICSMOVING							619
#define MANIFEST_COND_RAYHIT								615
#define MANIFEST_COND_SKDEVIATION							620
#define MANIFEST_COND_MESSAGECONDITION						601

// Transitions
#define MANIFEST_TRANSIT_TRANSIT							402
#define MANIFEST_TRANSIT_TRANSITMATCHEVENTS					400